# -*- coding: utf-8 -*-
"""Violence Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IPJBQRINlpfK8QxR__7hwQDQYgQlpuE2
"""

import numpy as np
import argparse
import pickle
import cv2
from google.colab.patches import cv2_imshow
import os
import time 
from keras.models import load_model
from collections import deque

def print_results(video, limit=None):
        if not os.path.exists('output'):
            os.mkdir('output')

        print("Loading model ...")
        model = load_model('/content/drive/MyDrive/Violence Detection/499A.h5')
        Q = deque(maxlen=128)
        vs = cv2.VideoCapture(video)
        writer = None
        (W, H) = (None, None)
        count = 0     
        while True:
            (grabbed, frame) = vs.read()
            if not grabbed:
                break
            if W is None or H is None:
                (H, W) = frame.shape[:2]

            output = frame.copy()
           
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (128, 128)).astype("float32")
            frame = frame.reshape(128, 128, 3) / 255

            preds = model.predict(np.expand_dims(frame, axis=0))[0]

            Q.append(preds)

            results = np.array(Q).mean(axis=0)
            i = (preds > 0.50)[0]
            label = i

            text_color = (0, 255, 0) 

            if label: 
                text_color = (0, 0, 255) 

            else:
                text_color = (0, 255, 0)

            text = "Violence: {}".format(label)
            FONT = cv2.FONT_HERSHEY_SIMPLEX 

            cv2.putText(output, text, (35, 50), FONT,1.25, text_color, 3) 

            if writer is None:

                fourcc = cv2.VideoWriter_fourcc(*"MJPG")
                writer = cv2.VideoWriter("output/v_output.avi", fourcc, 30,(W, H), True)

            writer.write(output)

            cv2_imshow(output)
            key = cv2.waitKey(1) & 0xFF

            if key == ord("q"):
                break

        print("[INFO] cleaning up...")
        writer.release()
        vs.release()

from google.colab import drive
drive.mount('/content/drive')

V_path = "/content/drive/MyDrive/Violence Detection/V_360.mp4"  
NV_path = "/content/drive/MyDrive/Violence Detection/V_4.mp4"

print_results(V_path)

